# Generated by Django 3.1.7 on 2021-03-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED'), ('RESOLVED', 'RESOLVED'), ('WAITING ON PART', 'WAITING ON PART'), ('OTHER', 'OTHER')], default='OPEN', max_length=25),
        ),
    ]
