# Generated by Django 3.1.7 on 2021-03-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210313_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='details',
            field=models.CharField(help_text='no more the 100 characters', max_length=25),
        ),
    ]
