# Generated by Django 3.1.7 on 2021-03-14 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210313_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='details',
            field=models.TextField(help_text='no more the 100 characters', max_length=100),
        ),
    ]
